ДЗ2
annavtropikah/2-nd-cours-hw pull request #2
Opened 2023-10-17 18:27 UTC by annavtropikah

2023-10-18 19:34 UTC, Mielilon requested changes
Хорошее решение, оставила несколько комментариев.

2023-10-18 19:34 UTC, Mielilon commented on hw2.js
> +// alert(a);
По условию задачи также требуется после вывода изменить значение переменной и после этого выполнить повторный вывод. Сейчас это не реализовано.

2023-10-18 19:34 UTC, mielilon commented on hw2.js
> +// let a=Number(10);
Нет необходимости преобразовывать число к числу, можем оставить так:
`let a = 10`

2023-10-18 19:34 UTC, Mielilon commented on hw2.js
> +// let b=Number(2);
Аналогично предыдущему комментарию.

2023-10-18 19:34 UTC, Mielilon commented on hw2.js
> +// let age=(prompt('Сколько вам лет?'));
Скобочки, оборачивающие `prompt` не нужны, их можно удалить.

2023-10-23 13:06 UTC, annavtropikah commented on hw2.js
> +// alert(a);
Дополнила

2023-10-24 15:26 UTC, merged